version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ia_recommendation
      - SECRET_KEY=your_secret_key_here
      - OLLAMA_BASE_URL=http://ollama:11434
      # - OLLAMA_NO_CUDA=1 # Pode manter se quiser forçar CPU, mas geralmente não é necessário aqui
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ia_recommendation
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ia_recommendation"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  ollama:
    image: ollama/ollama:0.7.0
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD", "/bin/ollama", "list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 180s

volumes:
  postgres_data:
  ollama_data: