version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ia_recommendation
      - OLLAMA_BASE_URL=http://ollama:11434

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ia_recommendation

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"

volumes:
  postgres_data: