name: CI/CD

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2 
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pip install poetry==1.8.2 

    - name: Install dependencies with Poetry
      run: poetry install --no-root --only main

    - name: Run tests
      run: poetry run pytest 

  deploy:
    needs: test 
    runs-on: ubuntu-latest 
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2 

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build and push Docker image
      env:
        DOCKER_IMAGE_NAME: seu-usuario-docker/ia-recommendation
      run: |
        # TAG da imagem com o SHA do commit (hash único do commit) para um versionamento específico
        IMAGE_TAG=${{ github.sha }}
        
        echo "Building Docker image: $DOCKER_IMAGE_NAME:$IMAGE_TAG"
        docker build -t $DOCKER_IMAGE_NAME:$IMAGE_TAG -t $DOCKER_IMAGE_NAME:latest .
        
        echo "Pushing Docker image: $DOCKER_IMAGE_NAME:$IMAGE_TAG and $DOCKER_IMAGE_NAME:latest"
        docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
        docker push $DOCKER_IMAGE_NAME:latest